//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JurassicRisk.Ressource
{
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JurassicRisk.Ressources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Affiche le titre du jeux
        /// </summary>
        public static string GameTitle
        {
            get
            {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Connexion
        /// </summary>
        public static string Connexion
        {
            get
            {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }

        /// <summary>
        ///   Inscription
        /// </summary>
        public static string Inscription
        {
            get
            {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Pseudo
        /// </summary>
        public static string Pseudo
        {
            get
            {
                return ResourceManager.GetString("Pseudo", resourceCulture);
            }
        }

        /// <summary>
        ///   Password
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        public static string Connecter
        {
            get
            {
                return ResourceManager.GetString("Connecter", resourceCulture);
            }
        }
        public static string Sinscrire
        {
            get
            {
                return ResourceManager.GetString("Sinscrire", resourceCulture);
            }
        }

        public static string Play
        {
            get
            {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }

        public static string Options
        {
            get
            {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }

        public static string Profil
        {
            get
            {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }

        public static string Menu
        {
            get
            {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }

        public static string Deconnexion
        {
            get
            {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }

        public static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        public static string NoExiste
        {
            get
            {
                return ResourceManager.GetString("NoExiste",resourceCulture);
            }
        }

        public static string NoPseudoEnter
        {
            get
            {
                return ResourceManager.GetString("NoPseudoEnter", resourceCulture);
            }
        }

        public static string PartieJoué
        {
            get
            {
                return ResourceManager.GetString("PartieJoué", resourceCulture);
            }
        }

        public static string TrpVaincus
        {
            get
            {
                return ResourceManager.GetString("TrpVaincus", resourceCulture);
            }
        }

        public static string TrpPerdus
        {
            get
            {
                return ResourceManager.GetString("TrpPerdus", resourceCulture);
            }
        }
        public static string TConquis
        {
            get
            {
                return ResourceManager.GetString("TConquis", resourceCulture);
            }
        }
        public static string TConquisSmlt
        {
            get
            {
                return ResourceManager.GetString("TConquisSmlt", resourceCulture);
            }
        }

        public static string FullScreen
        {
            get
            {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        public static string Musique
        {
            get
            {
                return ResourceManager.GetString("Musique", resourceCulture);
            }
        }

        public static string ConfimationMdp
        {
            get
            {
                return ResourceManager.GetString("ConfirationMdp", resourceCulture);
            }
        }

        public static string PasswordNotMatch
        {
            get
            {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        public static string PauseEm
        {
            get
            {
                return ResourceManager.GetString("PauseEm", resourceCulture);
            }
        }
        
        public static string TrpNombre
        {
            get
            {
                return ResourceManager.GetString("TrpNombre", resourceCulture);
            }
        }

        public static string NbTerritoireVide
        {
            get
            {
                return ResourceManager.GetString("NbTerritoireVide", resourceCulture);
            }
        }

        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string Lobby
        {
            get
            {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }

        public static string Ready
        {
            get
            {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }

        public static string Red
        {
            get
            {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }

        public static string Green
        {
            get
            {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }

        public static string Blue
        {
            get
            {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }

        public static string Yellow
        {
            get
            {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        public static string ErrorNotUnit
        {
            get
            {
                return ResourceManager.GetString("ErrorNotUnit", resourceCulture);
            }
        }
        public static string ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        public static string ErrorTerritory
        {
            get
            {
                return ResourceManager.GetString("ErrorTerritory", resourceCulture);
            }
                                        
        }
        

        public static string CreateLobby
        {
            get
            {
                return ResourceManager.GetString("CreateLobby", resourceCulture);
            }
        }

        public static string JoinLobby
        {
            get
            {
                return ResourceManager.GetString("JoinLobby", resourceCulture);
            }
        }
        public static string NoExistLobby
        {
            get
            {
                return ResourceManager.GetString("NoExistLobby", resourceCulture);
            }
        }      
    }
}
